# Generated by Django 4.2.3 on 2023-07-11 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_photo_number_user_phone_number_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97cbca02-a379-4235-baf2-e28d5021a35f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97cbca02-a379-4235-baf2-e28d5021a35f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
