# Generated by Django 5.0.6 on 2024-06-01 07:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4f0490a7-97fd-43c4-a323-119e490ba50c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4f0490a7-97fd-43c4-a323-119e490ba50c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
